### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by KlinkerJ** [lennart2810/sdm#1]
Lass uns die Dateien mal ordentlich dokumentieren @lennart2810, in drei Monaten versteht sonst keiner mehr den Unterschied zwischen [gui_test.ino](https://github.com/lennart2810/sdm/blob/master/scripts/gui_test/gui_test.ino) und [controllino_gui_lageregler.ino](https://github.com/lennart2810/sdm/blob/master/scripts/controllino_gui_lageregler/controllino_gui_lageregler.ino), dafür brauch ich aber auch noch etwas Input von Dir.

**Comment by lennart2810** [comment]
Da die beiden scripte überflüssig sind, schmeißen wie sie einfach raus 😸
